# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2024, daniyl-x


- name: Install pip
  package:
    name: python3-pip
    state: present

- name: Install podman-compose from pip
  pip:
    name: podman-compose
    extra_args: --break-system-packages
    # TODO: The next parameter requires ansible-core > 2.7,
    # which i don't have yet so using the approach above 
    # break_system_packages: true

