# Copyright (c) 2024 daniyl-x
# Licensed under BSD-1-Clause License.


- name: Manage packages
  hosts: all
  become: true

  tasks:
    - name: Update apt packages
      apt:
        name: "*"
        state: latest
        update_cache: true
        cache_valid_time: 3600
      when: ansible_facts["os_family"] == "Debian"

    - name: Install apt packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
      when: ansible_facts["os_family"] == "Debian"


- name: Configure system
  hosts: all
  become: true

  tasks:
    - name: Disable SSH server options
      replace:
        path: /etc/ssh/sshd_config
        regexp: "^({{ item }} (?!no)|#{{ item }}).*"
        replace: "{{ item }} no"
      loop:
        - PasswordAuthentication
        - PermitRootLogin
      notify: Restart SSH server

    - name: Enable current user lingering
      file:
        path: "/var/lib/systemd/linger/{{ ansible_user }}"
        state: touch
        modification_time: preserve
        access_time: preserve

    - name: Reduce swappiness
      sysctl:
        name: vm.swappiness
        value: 10
      notify: Reboot

  handlers:
    - name: Restart SSH server
      service:
        name: sshd
        state: restarted

    - name: Reboot
      reboot:


- name: Install dotfiles
  hosts: all

  tasks:
    - name: Pull dotfiles
      git:
        repo: "https://github.com/daniyl-x/dotfiles"
        dest: "/home/{{ ansible_user }}/dotfiles"

    - name: Enumerate dotfiles directories
      find:
        paths: "/home/{{ ansible_user }}/dotfiles"
        file_type: directory
        # This parameter uses globs, not regex
        excludes: ".*"
      register: available_dotfiles

    - name: Process and store available dotfiles
      set_fact:
        available_dotfiles: >
          {{ available_dotfiles.files | map(attribute='path')
          | map('basename') | list }}"

    - name: Create ~/.config directory
      file:
        path: "/home/{{ ansible_user }}/.config"
        state: directory
        modification_time: preserve
        access_time: preserve

    - name: Install dotfiles with GNU Stow
      command:
        cmd: "stow -t /home/{{ ansible_user }} {{ item }}"
        chdir: "/home/{{ ansible_user }}/dotfiles"
      loop: "{{ dotfiles }}"
      when: item in available_dotfiles

