# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2024-2025, daniyl-x


- name: Update system and manage packages
  hosts: all
  become: true

  vars:
    required_packages:
      - git

  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_facts["os_family"] == "Debian"

    - name: Update packages
      package:
        name: "*"
        state: latest

    - name: Install packages
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ packages + required_packages }}"

    - name: Get out!
      package:
        name: "{{ item }}"
        state: absent
      loop:
        - nano


- name: Configure SSH
  hosts: all

  pre_tasks:
    - name: Read public SSH key
      slurp:
        path: "{{ ansible_ssh_private_key_file }}.pub"
      delegate_to: localhost
      register: public_ssh_key

    - name: Add the key to ~/.ssh/authorized_keys
      lineinfile:
        path: "{{ ansible_user_dir }}/.ssh/authorized_keys"
        line: "{{ public_ssh_key.content | b64decode | trim }}"
        create: true

  tasks:
    - name: Explicitly enable key-based SSH authentication
      replace:
        path: /etc/ssh/sshd_config
        regexp: "^({{ item }} (?!yes)|#{{ item }}).*"
        replace: "{{ item }} yes"
      loop:
        - PubkeyAuthentication
      notify: Restart SSH server
      become: true

    - name: Disable SSH server options
      replace:
        path: /etc/ssh/sshd_config
        regexp: "^({{ item }} (?!no)|#{{ item }}).*"
        replace: "{{ item }} no"
      loop:
        - PasswordAuthentication
        - PermitRootLogin
        - KbdInteractiveAuthentication
      notify: Restart SSH server
      become: true

  handlers:
    - name: Restart SSH server
      service:
        name: sshd
        state: restarted
      become: true


- name: Apply basic configuration
  hosts: all
  become: true

  tasks:
    - name: Enable current user lingering
      file:
        path: "/var/lib/systemd/linger/{{ ansible_user }}"
        state: touch
        modification_time: preserve
        access_time: preserve

    - name: Reduce swappiness
      sysctl:
        name: vm.swappiness
        value: 10
      notify: Reboot

  handlers:
    - name: Reboot
      reboot:


- name: Configure additional software
  hosts: all
  become: true

  roles:
    - role: podman_compose
      when: "'podman' in packages"

  tasks:
    - name: Enable iperf3
      service:
        name: iperf3
        enabled: true
        state: started
      when: "'iperf3' in packages"

    - name: Install Cockpit Podman plugin
      package:
        name: cockpit-podman
        state: present
      when: "'cockpit' in packages and 'podman' in packages"

    - name: Configure Cockpit for reverse proxy
      blockinfile:
        path: /etc/cockpit/cockpit.conf
        create: true
        block: |
          [WebService]
          ProtocolHeader=X-Forwarded-Proto
          UrlRoot=/cockpit/
      notify: Restart Cockpit
      when: "'cockpit' in packages"

  handlers:
    - name: Restart Cockpit
      service:
        name: cockpit
        state: restarted


- name: Install containers repository
  hosts: all

  roles:
    - role: containers_repository
      when: "'podman' in packages or 'docker' in packages"


- name: Install dotfiles
  hosts: all

  vars:
    dotfiles_dir: "{{ ansible_user_dir }}/dotfiles"

  pre_tasks:
    - name: Pull dotfiles repository
      git:
        repo: "https://github.com/daniyl-x/dotfiles"
        dest: "{{ dotfiles_dir }}"
        version: main

    - name: Copy dotfiles to ~/
      copy:
        src: "{{ dotfiles_dir }}/{{ item }}/"
        dest: "{{ ansible_user_dir }}"
        remote_src: true
      loop: "{{ dotfiles }}"

  roles:
    - role: fzf_scripts
      when: "'fzf' in packages"

    - role: vim_plugins
      when: "'vim' in dotfiles"

