# Copyright (c) 2024 daniyl-x
# Licensed under BSD-1-Clause License.


- name: Update packages
  hosts: all
  become: true

  tasks:
    - name: Update apt packages
      apt:
        name: "*"
        state: latest
        update_cache: true
        cache_valid_time: 3600
      when: ansible_facts["os_family"] == "Debian"

