# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2024, daniyl-x


- name: Copy get_fzf_tag.awk to the target
  copy:
    src: get_fzf_tag.awk
    dest: /tmp/get_fzf_tag.awk
    mode: 0400

- name: Get fzf tag
  shell: "awk -f /tmp/get_fzf_tag.awk"
  register: fzf_tag
  changed_when: false

- name: Store fzf tag
  set_fact:
    fzf_tag: "{{ fzf_tag.stdout }}"

- name: Create fzf scripts directory
  file:
    path: "{{ fzf_scripts_dir }}"
    state: directory
    mode: a+rx
    modification_time: preserve
    access_time: preserve
  become: true

- name: Pull fzf scripts
  uri:
    url: "https://raw.githubusercontent.com/junegunn/fzf/refs/tags/{{ fzf_tag }}/shell/{{ item }}"
    dest: "{{ fzf_scripts_dir }}/{{ item }}"
    mode: a+rx
    follow_redirects: all
    status_code: [200, 404]
    creates: "{{ fzf_scripts_dir }}/{{ item }}"
  # Combine scripts with shell extensions
  loop: "{{ fzf_scripts | product(fzf_shells) | map('join', '.')}}"
  become: true

