# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2024-2025, daniyl-x


- name: Pull containers repository
  git:
    repo: https://github.com/daniyl-x/containers
    dest: "{{ containers_repo_dir }}"
    version: main

- name: Get VOLUME_PREFIX from ~/containers/.env
  shell: ". {{ containers_env_file }} && echo $VOLUME_PREFIX"
  register: containers_volume_prefix
  changed_when: false

- name: Create VOLUME_PREFIX directory
  file:
    path: "{{ containers_volume_prefix.stdout }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    modification_time: preserve
    access_time: preserve
  become: true

- name: Generate self signed certificate for NGINX
  shell:
    cmd: "./../../generate-ssl-cert.sh {{ ansible_hostname }}"
    chdir: "{{ containers_repo_dir }}/nginx/config/ssl/"
  changed_when: false

