# Copyright (c) 2024 daniyl-x
# Licensed under BSD-1-Clause License.


- name: Install Vim
  package:
    name: vim
    state: present

- name: Create ~/.vim/autoload directory
  file:
    path: "{{ vim_autoload_dir }}"
    state: directory
    modification_time: preserve
    access_time: preserve

- name: Pull Vim Plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ vim_autoload_dir }}/plug.vim"

- name: Update and clean Vim plugins
  shell: "vim -s ~/.vimrc +PlugUpdate +PlugClean +qa"

